INSERT INTO ITEM (ITEM_NUMBER , IMAGE_URL , ITEM_NAME ,PRICE ,PRICE_EACH_QUANTITY  ,QUANTITY ) values(111,'junk','tide', 0.0,12.0,10);
INSERT INTO ITEM (ITEM_NUMBER , IMAGE_URL , ITEM_NAME ,PRICE ,PRICE_EACH_QUANTITY  ,QUANTITY ) values(222,'junk','fan', 0.0,12.0,10);
INSERT INTO ITEM (ITEM_NUMBER , IMAGE_URL , ITEM_NAME ,PRICE ,PRICE_EACH_QUANTITY  ,QUANTITY ) values(333,'junk','iphone', 0.0,12.0,10);
INSERT INTO ITEM (ITEM_NUMBER , IMAGE_URL , ITEM_NAME ,PRICE ,PRICE_EACH_QUANTITY  ,QUANTITY ) values(444,'junk','samsung galaxy', 0.0,12.0,10);
INSERT INTO ITEM (ITEM_NUMBER , IMAGE_URL , ITEM_NAME ,PRICE ,PRICE_EACH_QUANTITY  ,QUANTITY ) values(555,'junk','nokia', 0.0,12.0,10);
INSERT INTO ITEM (ITEM_NUMBER , IMAGE_URL , ITEM_NAME ,PRICE ,PRICE_EACH_QUANTITY  ,QUANTITY ) values(666,'junk','milton', 0.0,12.0,10);
INSERT INTO ITEM (ITEM_NUMBER , IMAGE_URL , ITEM_NAME ,PRICE ,PRICE_EACH_QUANTITY  ,QUANTITY ) values(777,'junk','nike shoe', 0.0,12.0,10);
INSERT INTO ITEM (ITEM_NUMBER , IMAGE_URL , ITEM_NAME ,PRICE ,PRICE_EACH_QUANTITY  ,QUANTITY ) values(888,'junk','tshirt', 0.0,12.0,10);